### ISSUE TITLE
Document using Spegel with pull through registries

### ISSUE THREAD

**Issue by phillebaba** [XenitAB/spegel#277]
> After carefully reviewing the following containerd-related errors, I deleted the configurations related to "mirror" in `/etc/rancher/k3s/registries.yaml` and `/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl`. Now, `spegel` is working properly.
> 
> ```shell
> time="2023-11-20T23:28:55.907708354+08:00" level=warning msg="failed to load plugin io.containerd.grpc.v1.cri" error="invalid plugin config: `mirrors` cannot be set when `config_path` is provided"
> ```

That's a bit unfortunate since the docs state:

> Spegel does not aim to replace projects like [Harbor](https://github.com/goharbor/harbor) or [Zot](https://github.com/project-zot/zot) but instead complements them.

I was hoping to use spegel in my cluster and zot as a pull thru cache deployed elsewhere. For what it's worth this is my current containerd mirrors:

```yaml
mirrors:
  docker.io:
    endpoint:
      - https://zot.domain.tld/v2/docker.io
  ghcr.io:
    endpoint:
      - https://zot.domain.tld/v2/ghcr.io
  quay.io:
    endpoint:
      - https://zot.domain.tld/v2/quay.io
  gcr.io:
    endpoint:
      - https://zot.domain.tld/v2/gcr.io
  registry.k8s.io:
    endpoint:
      - https://zot.domain.tld/v2/registry.k8s.io
  public.ecr.aws:
    endpoint:
      - https://zot.domain.tld/v2/public.ecr.aws
```

I don't see a way to have spegel take over this responsibility it seems like you either have spegel or a pull thru cache, maybe this can be a feature request?

_Originally posted by @onedr0p in https://github.com/XenitAB/spegel/issues/212#issuecomment-1830879118_

**Comment by phillebaba** [comment]
@onedr0p I created a new issue for this as it is not realted to k3s, and can be fixed with more documentation.

**Comment by onedr0p** [comment]
Thanks @phillebaba, in the meantime do you have any tips on how to get that working? I don't mind contributing to the docs if I can get it working on my end.

**Comment by phillebaba** [comment]
Could you check the docs added to #280 and see if this is enough?

**Comment by onedr0p** [comment]
For example

```yaml
spegel:
  additionalMirrorRegistries:
    - https://zot.example.com                       # not sure only the base domain would work?
    - https://zot.example.com/v2/docker.io # how would spegel know to pull dockerhub images from here?
```
