### ISSUE TITLE
Images not updated even with k8s-digester

### ISSUE THREAD

**Issue by craigcabrey** [XenitAB/spegel#295]
Hi,

Thanks for developing this project! I've read the FAQ around image tags & how they affect spegel's behavior. I have multiple images setup using `latest` (I understand the dangers here, this is for a homelab so low risk) and am not seeing the images get updated. I have deployed k8s-digester and see it resolves the tags to a digest:

```
  - image: ghcr.io/home-assistant/home-assistant:stable@sha256:93b9ebc8a464475f42113ccf121bb3c495ce2b4adc0a6fe2c7c3946a5912e850
```

Reading the docs, it says:

> This means that k8s-digester will resolve the new digest for a tag if a new version is pushed to the registry.

This part was not clear to me. I read it as k8s-digester actively polls registries for tag updates. However their documentation doesn't reference this behavior at all. I also don't see this happening.

Ultimately, I am a bit unclear on which components are responsible for which behaviors. Clearly, spegel is responsible for serving up images in the node caches. k8s-digester resolves tags to digests. But which piece polls the registries for new images remains a bit of a mystery.

Could you help clarify this?
Thanks!

**Comment by phillebaba** [comment]
k8s-digester does not actively poll registries but resolves the tag every time its webhook is called. The wording of my documentation may be a bit misleading. I made some assumptions about k8s-digester behavior that were wrong, I have just not had time to update the documentation. My assumption was that k8s-digester would resolve the tag for every Pod created. This is however not the case. Instead the mutating webhook is configured to mutate when creating deployments, daemonsets or statefulsets also.
https://github.com/google/k8s-digester/blob/main/manifests/mutating-webhook-configuration.yaml

If the Pod has a digest set in the image it will not be mutated again.
https://github.com/google/k8s-digester/blob/d7c54fa99a7fa6bbb23f2e28c0321a07021eceb9/pkg/resolve/resolve.go#L108-L110

That means that if the deployment has been mutated any pods created will not be. Resulting in the digest being set once and never again.

We need to doument that the mutating webhook needs to be modified to only mutate Pods. This would cause the digeset to be updated every time a pod is created.
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: digester-mutating-webhook-configuration
  labels:
    control-plane: controller-manager
    digester/operation: webhook
    digester/system: "yes"
webhooks:
- name: digester-webhook-service.digester-system.svc
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: digester-webhook-service
      namespace: digester-system
      path: /v1/mutate
    caBundle: Cg==
  failurePolicy: Ignore # kpt-set: ${failure-policy}
  namespaceSelector:
    matchLabels:
      digest-resolution: enabled
  reinvocationPolicy: IfNeeded
  rules:
  - resources:
    - pods
    apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 15
```
