### ISSUE TITLE
Improve configuration tooling

### ISSUE THREAD

**Issue by bc185174** [XenitAB/spegel#312]
### Describe the problem to be solved

Spegel can be configured through the helm chart values which are propagated to the container arguments; however, there is currently no mechanic to allow end users to configure the application through a config map. This will also be useful when other deployment tooling like kustomizations are used.

### Proposed solution to the problem

Switch to using `github.com/peterbourgon/ff/v3` to parse arguments or env vars.

As an example.

```yaml
        containers:
        - args:
          - --mirror-resolve-retries=3
          - --mirror-resolve-timeout=3s
```

Create a config map:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
  namespace: spegel
data:
  MIRROR_RESOLVE_RETRIES: "3"
  MIRROR_RESOLVE_TIMEOUT: 3s
```

Consume the config map:

```yaml
        containers:
          envFrom:
          - configMapRef:
              name: configuration
```
