### ISSUE TITLE
0.0.17 release incorrect version configured

### ISSUE THREAD

**Issue by bc185174** [XenitAB/spegel#332]
### Spegel version

v0.0.017

### Kubernetes distribution

Kubeadm

### Kubernetes version

v1.27.7

### CNI

Calico

### Describe the bug

Not sure if this was intential, but the release for `v0.0.17` references version `v0.0.1`. Snippet from chart rendering:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spegel
  namespace: spegel
  labels:
    helm.sh/chart: spegel-v0.0.1
    app.kubernetes.io/name: spegel
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/version: "v0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  updateStrategy:
    {}
  selector:
    matchLabels:
      app.kubernetes.io/name: spegel
      app.kubernetes.io/instance: spegel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spegel
        app.kubernetes.io/instance: spegel
    spec:
      serviceAccountName: spegel
      securityContext:
        {}
      priorityClassName: system-node-critical
      initContainers:
      - name: configuration
        image: "ghcr.io/xenitab/spegel:v0.0.1"
        imagePullPolicy: IfNotPresent
```
